name: Crowdin mobile source push

on:
  push:
    paths:
        - 'translation/source/mobile.xml'
    branches: [ main ]
  workflow_dispatch:

jobs:
  crowdin-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          source: translation/source/mobile.xml
          translation: /translation/dest/%file_name%/%locale%.%file_extension%
          crowdin_branch_name: '[lichess-org.mobile] main'
          upload_sources_args: '--preserve-hierarchy'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
