name: Upload the F-Droid APK to Github
# Enable manual run
on: workflow_dispatch

# Declare default permissions as read only.
permissions: read-all

jobs:
  github-upload:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags') && endsWith(github.ref, 'fdroid') # only runs for fdroid tags
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - run: flutter doctor -v

      - name: Checkout mobile code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build

      - name: Build the APK
        run: flutter build apk --dart-define=cronetHttpNoPlay=true --dart-define=LICHESS_HOST=lichess.org --dart-define=LICHESS_WS_HOST=socket.lichess.org --dart-define=LICHESS_WS_SECRET=wG1OLhUR3CSXdDybqrtIW227QGrtiM3d

      - name: Upload the APK
        uses: actions/upload-artifact@v6
        with:
          path: build/app/outputs/flutter-apk/app-release.apk

